name: "get repo stats"
on: [issues, pull_request, workflow_dispatch]

jobs:
  repo-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get stats from action
        id: stats
        uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      
      - name: print stats
        run: |
          echo "PR stats: ${{ steps.stats.outputs.pull_request_stats }}"
          echo "PR stats: ${{ steps.stats.outputs.issue_stats }}"